#include "instruction.h"

instruction instructions[0x100] = {
    // 0x0X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x1X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x2X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x3X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x4X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x5X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x6X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x7X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x8X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0x9X
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0xAX
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0xBX
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0xCX
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0xDX
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0xEX
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },

    // 0xFX
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
    { OP_NOP },
};
